#!/usr/bin/env python3
#-*- coding:utf-8 -*-

'a Student demo2510- created on 2015-10-25'

__author = 'Dylan Lang'

import sys

class Student:
	
	name = 'Student'

	def set_age(self,age):
		self.age = age